# uv configuration for Reading Journey Backend
[tool.uv]
managed = true
python-preference = "only-managed"
python-downloads = "automatic"

# Python version requirement
requires-python = ">=3.10,<3.11"

# Development dependencies that should be installed in dev environments
dev-dependencies = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "black>=23.7.0",
    "flake8>=6.1.0",
    "mypy>=1.5.0",
    "pre-commit>=3.3.3",
    "boto3-stubs[essential]>=1.28.0",
    "moto[s3,lambda,iam]>=4.2.0",
    "cfn-lint>=0.83.0"
]

# Cache configuration
cache-dir = ".uv-cache"

# Index configuration (for faster resolution)
index-strategy = "unsafe-best-match"

# Compile bytecode for faster imports
compile-bytecode = true

# Link mode for packages
link-mode = "copy"
